export const clients = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.j@company.com",
    status: "active",
    totalSpent: 15420,
    joinedDate: "2024-01-15",
  },
  {
    id: "2",
    name: "James Martinez",
    email: "james.m@tech.com",
    status: "active",
    totalSpent: 42100,
    joinedDate: "2023-08-10",
  },
  {
    id: "3",
    name: "Emma Wilson",
    email: "emma@design.co",
    status: "pending",
    totalSpent: 5200,
    joinedDate: "2024-03-01",
  },
  {
    id: "4",
    name: "Lisa Anderson",
    email: "l.anderson@corp.com",
    status: "inactive",
    totalSpent: 9800,
    joinedDate: "2024-02-14",
  },
  {
    id: "5",
    name: "David Kim",
    email: "david.k@business.net",
    status: "active",
    totalSpent: 18750,
    joinedDate: "2023-12-05",
  },
  {
    id: "6",
    name: "Michael Chen",
    email: "m.chen@startup.io",
    status: "active",
    totalSpent: 28350,
    joinedDate: "2023-11-20",
  },
];
